apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -o passengersapi.yml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: mssql
    name: mssql
  spec:
    ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
    selector:
      io.kompose.service: mssql
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -o passengersapi.yml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: passengersapi
    name: passengersapi
  spec:
    ports:
    - name: "8082"
      port: 8082
      targetPort: 80
    - name: "44344"
      port: 44344
      targetPort: 443
    selector:
      io.kompose.service: passengersapi
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -o passengersapi.yml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: mssql
    name: mssql
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: mssql
      spec:
        containers:
        - env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: TestPassword1!
          image: mcr.microsoft.com/mssql/server:2017-latest
          name: mssql
          ports:
          - containerPort: 1433
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -o passengersapi.yml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: passengersapi
    name: passengersapi
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: passengersapi
      spec:
        containers:
        - env:
          - name: ASPNETCORE_HTTPS_PORT
            value: "44343"
          - name: ASPNETCORE_URLS
            value: https://+:443;http://+:80
          - name: SQLSERVER_HOST
            value: mssql
          - name: SQLSERVER_SA_PASSWORD
            value: TestPassword1!
          image: registry.gitlab.com/fvgoulet/api-exercise/passengersapi:latest
          name: passengersapi
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

